### ISSUE TITLE
Issue in Makefile

### ISSUE THREAD

**Issue by alexklimek1** [decathinator/DATA-550-SP24-ZHUANG#1]
Hi Cathy, I just did your peer review for DATA 550. It seems like there is an error when trying to make the file when I put "make final_report.html". I see that your final report html is there and all of your code is there so I know it should work, however there is an error when trying to use the makefile. The error is below. Additionally, I would add a statement to your Makefile to "make clean", because this might be contributing to the issue. Good luck and good job!

make: *** No rule to make target `\', needed by `derived_data/kPMdataLAB.rds'.  Stop.

**Comment by decathinator** [comment]
Thanks! I changed my Makefile. Hopefully it works now!
